import type { User } from './models';

export const mockUsers: User[] = [
  { id: 1, name: 'John Doe', email: 'john.doe@example.com', role: 'Admin', status: 'Active', joinDate: '2023-01-15' },
  { id: 2, name: 'Jane Smith', email: 'jane.smith@example.com', role: 'User', status: 'Active', joinDate: '2023-02-20' },
  { id: 3, name: 'Robert Johnson', email: 'robert.j@example.com', role: 'User', status: 'Suspended', joinDate: '2023-03-10' },
  { id: 4, name: 'Emily Davis', email: 'emily.davis@example.com', role: 'User', status: 'Pending', joinDate: '2023-04-05' },
  { id: 5, name: 'Michael Wilson', email: 'michael.w@example.com', role: 'User', status: 'Active', joinDate: '2023-05-12' },
  { id: 6, name: 'Sarah Brown', email: 'sarah.brown@example.com', role: 'Admin', status: 'Active', joinDate: '2023-06-18' },
  { id: 7, name: 'David Miller', email: 'david.m@example.com', role: 'User', status: 'Active', joinDate: '2023-07-22' },
  { id: 8, name: 'Lisa Taylor', email: 'lisa.t@example.com', role: 'User', status: 'Pending', joinDate: '2023-08-30' },
  { id: 9, name: 'James Anderson', email: 'james.a@example.com', role: 'User', status: 'Suspended', joinDate: '2023-09-14' },
  { id: 10, name: 'Maria Thomas', email: 'maria.t@example.com', role: 'User', status: 'Active', joinDate: '2023-10-08' },
  { id: 11, name: 'Daniel Jackson', email: 'daniel.j@example.com', role: 'User', status: 'Active', joinDate: '2023-11-25' },
  { id: 12, name: 'Sophia White', email: 'sophia.w@example.com', role: 'User', status: 'Pending', joinDate: '2023-12-01' },
  { id: 13, name: 'Matthew Harris', email: 'matthew.h@example.com', role: 'Admin', status: 'Suspended', joinDate: '2024-01-19' },
  { id: 14, name: 'Olivia Martin', email: 'olivia.m@example.com', role: 'User', status: 'Active', joinDate: '2024-02-11' },
  { id: 15, name: 'Andrew Thompson', email: 'andrew.t@example.com', role: 'User', status: 'Active', joinDate: '2024-03-05' },
  { id: 16, name: 'Emma Garcia', email: 'emma.g@example.com', role: 'User', status: 'Pending', joinDate: '2024-04-22' },
  { id: 17, name: 'Joshua Martinez', email: 'joshua.m@example.com', role: 'User', status: 'Active', joinDate: '2024-05-30' },
  { id: 18, name: 'Ava Robinson', email: 'ava.r@example.com', role: 'User', status: 'Suspended', joinDate: '2024-06-17' },
  { id: 19, name: 'Christopher Clark', email: 'chris.c@example.com', role: 'Admin', status: 'Active', joinDate: '2024-07-08' },
  { id: 20, name: 'Isabella Rodriguez', email: 'isabella.r@example.com', role: 'User', status: 'Active', joinDate: '2024-08-25' },
  { id: 21, name: 'Joseph Lewis', email: 'joseph.l@example.com', role: 'User', status: 'Pending', joinDate: '2024-09-12' },
  { id: 22, name: 'Mia Lee', email: 'mia.lee@example.com', role: 'User', status: 'Active', joinDate: '2024-10-03' },
  { id: 23, name: 'William Walker', email: 'william.w@example.com', role: 'User', status: 'Suspended', joinDate: '2024-11-28' },
  { id: 24, name: 'Charlotte Hall', email: 'charlotte.h@example.com', role: 'User', status: 'Active', joinDate: '2024-12-15' },
  { id: 25, name: 'Ethan Young', email: 'ethan.y@example.com', role: 'Admin', status: 'Pending', joinDate: '2025-01-07' },
];
